// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Balanza_Registro_Pesaje', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Balanza_Registro_Pesaje', async function() {
    await driver.get("https://landing-test.vuce.gob.pe/vuce-zee-api-autorizacion/login/?urlReturn=https://landing-test.vuce.gob.pe/vuce-zee-mf/")
    await driver.manage().window().setRect({ width: 1552, height: 832 })
    await driver.findElement(By.id("username")).click()
    await driver.findElement(By.id("password")).click()
    await driver.findElement(By.css(".btn-danger")).click()
    await driver.findElement(By.css(".ng-tns-c50-22 > .mat-expansion-panel-header-title")).click()
    await driver.findElement(By.id("mat-expansion-panel-header-29")).click()
    {
      const element = await driver.findElement(By.css(".mat-raised-button:nth-child(3) > .mat-button-wrapper"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".cdk-focused > .mat-button-wrapper")).click()
    await driver.findElement(By.css("#mat-select-value-7 > .mat-select-placeholder")).click()
    await driver.findElement(By.css("#mat-option-12 > .mat-option-text")).click()
    await driver.findElement(By.css(".mat-card-content:nth-child(2)")).click()
    await driver.findElement(By.id("mat-input-10")).click()
    await driver.findElement(By.id("mat-input-10")).sendKeys("RD/ZEE-2024-64")
    await driver.findElement(By.css("body")).click()
    {
      const element = await driver.findElement(By.css(".cdk-focused"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".cdk-focused")).click()
    await driver.findElement(By.css("#mat-select-value-9 > .mat-select-placeholder")).click()
    await driver.findElement(By.css(".mat-option-text")).click()
    await driver.findElement(By.id("mat-input-15")).click()
    await driver.findElement(By.id("mat-input-15")).sendKeys("400")
    await driver.findElement(By.css(".ng-invalid > .mat-card:nth-child(3)")).click()
    await driver.executeScript("window.scrollTo(0,668.7999877929688)")
    await driver.findElement(By.css(".cdk-focused")).click()
    await driver.executeScript("window.scrollTo(0,0)")
    await driver.findElement(By.css(".mat-overlay-transparent-backdrop")).click()
    await driver.findElement(By.id("mat-input-27")).click()
    await driver.findElement(By.id("mat-input-27")).sendKeys("400")
    await driver.findElement(By.css(".cdk-overlay-backdrop")).click()
    await driver.findElement(By.css(".mat-overlay-transparent-backdrop")).click()
    await driver.findElement(By.css(".cdk-focused > .mat-button-wrapper")).click()
    {
      const element = await driver.findElement(By.css(".cdk-focused > .mat-button-wrapper"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".cdk-focused > .mat-button-wrapper")).click()
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.executeScript("window.scrollTo(0,0)")
    await driver.findElement(By.css(".mat-overlay-transparent-backdrop")).click()
    await driver.findElement(By.css(".ng-tns-c57-72 > .mat-form-field-infix")).click()
    {
      const element = await driver.findElement(By.css(".mat-warn:nth-child(2) > .mat-button-wrapper"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.id("mat-input-29")).sendKeys("500")
    await driver.findElement(By.css(".cdk-focused > .mat-button-wrapper")).click()
    await driver.findElement(By.css(".mat-row:nth-child(2) > .cdk-column-segundoPesaje")).click()
    {
      const element = await driver.findElement(By.css(".buttons-group:nth-child(2) > .mat-focus-indicator:nth-child(1) > .mat-button-wrapper"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".cdk-focused > .mat-button-wrapper")).click()
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.executeScript("window.scrollTo(0,0)")
    {
      const element = await driver.findElement(By.css(".cdk-focused"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".cdk-focused")).click()
    await driver.executeScript("window.scrollTo(0,0)")
  })
})
