// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Contrato_Registro_Inversion_contrato', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Contrato_Registro_Inversion_contrato', async function() {
    await driver.get("https://landing-test.vuce.gob.pe/vuce-zee-api-autorizacion/login/?urlReturn=https://landing-test.vuce.gob.pe/vuce-zee-mf/")
    await driver.manage().window().setRect({ width: 1032, height: 816 })
    await driver.findElement(By.css(".btn-danger")).click()
    await driver.findElement(By.css(".ng-tns-c50-44 > .text-bold-e503492c-335d-4d2a-80e6-d3348e100146")).click()
    await driver.findElement(By.css(".ng-tns-c50-166 > .second-ce6de76e-7965-48da-8a62-cabdb813e076")).click()
    await driver.executeScript("window.scrollTo(0,0)")
    await driver.findElement(By.id("mat-input-0")).click()
    await driver.findElement(By.id("mat-input-0")).sendKeys("CT/ZEE-2024-43")
    await driver.findElement(By.css(".ng-tns-c139-6 > .mat-form-field-infix")).click()
    {
      const element = await driver.findElement(By.css(".mat-calendar-period-button > .mat-button-wrapper"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".mat-calendar-period-button > .mat-button-wrapper")).click()
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.css(".ng-star-inserted:nth-child(1) > .mat-calendar-body-cell:nth-child(1) > .mat-calendar-body-cell-content")).click()
    await driver.findElement(By.css(".mat-calendar-body-active > .mat-calendar-body-cell-content")).click()
    await driver.findElement(By.css(".ng-star-inserted:nth-child(2) > .mat-calendar-body-cell:nth-child(1) > .mat-calendar-body-cell-content")).click()
    {
      const element = await driver.findElement(By.css(".mat-card-actions > .mat-focus-indicator:nth-child(1) > .mat-button-wrapper"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".cdk-focused > .mat-button-wrapper")).click()
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    {
      const element = await driver.findElement(By.css(".table-container-d60dd7df-5bbb-4aad-b9b8-f46be2a80570"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    {
      const element = await driver.findElement(By.css(".table-container-d60dd7df-5bbb-4aad-b9b8-f46be2a80570"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.css(".table-container-d60dd7df-5bbb-4aad-b9b8-f46be2a80570"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    await driver.executeScript("window.scrollTo(0,164.8000030517578)")
    await driver.findElement(By.css(".cdk-focused .mat-icon")).click()
    await driver.executeScript("window.scrollTo(0,0)")
    await driver.findElement(By.css(".cdk-focused > .mat-button-wrapper")).click()
    await driver.findElement(By.css("#mat-select-value-21 > .mat-select-placeholder")).click()
    await driver.findElement(By.css("#mat-select-value-21 > .mat-select-placeholder")).click()
    await driver.findElement(By.css(".ng-tns-c139-50 > .mat-form-field-infix")).click()
    await driver.findElement(By.css(".ng-tns-c139-52 > .mat-form-field-infix")).click()
    await driver.findElement(By.css("#mat-option-149 > .mat-option-text")).click()
    await driver.findElement(By.id("mat-input-7")).click()
    await driver.findElement(By.id("mat-input-7")).sendKeys("1")
    await driver.findElement(By.css(".ng-tns-c139-55 > .mat-form-field-infix")).click()
    await driver.findElement(By.id("mat-input-8")).sendKeys("2")
    await driver.findElement(By.css(".ng-tns-c139-57 > .mat-form-field-infix")).click()
    await driver.findElement(By.id("mat-input-10")).sendKeys("4")
    await driver.findElement(By.css(".ng-tns-c139-58 > .mat-form-field-infix")).click()
    await driver.findElement(By.id("mat-input-11")).sendKeys("1.5")
    await driver.findElement(By.id("mat-input-12")).click()
    await driver.findElement(By.id("mat-input-12")).sendKeys("2.5")
    await driver.findElement(By.css(".cdk-focused > .mat-button-wrapper")).click()
    await driver.findElement(By.css(".cdk-focused > .mat-button-wrapper")).click()
    await driver.findElement(By.css(".cdk-focused > .mat-button-wrapper")).click()
  })
})
