// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Crear_Notificacion_Mensajeria', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Crear_Notificacion_Mensajeria', async function() {
    await driver.get("https://landing-test.vuce.gob.pe/vuce-zee-api-autorizacion/login/?urlReturn=https://landing-test.vuce.gob.pe/vuce-zee-mf/")
    await driver.manage().window().setRect({ width: 1936, height: 1048 })
    await driver.findElement(By.id("username")).click()
    await driver.findElement(By.id("username")).sendKeys("abelchingo")
    await driver.findElement(By.id("password")).sendKeys("admin")
    await driver.findElement(By.css(".btn-danger")).click()
    await driver.findElement(By.id("mat-expansion-panel-header-17")).click()
    await driver.findElement(By.css(".ng-tns-c50-160 > .second-ce6de76e-7965-48da-8a62-cabdb813e076")).click()
    await driver.findElement(By.css(".cdk-focused > .mat-button-wrapper")).click()
    await driver.findElement(By.id("mat-input-4")).click()
    await driver.findElement(By.id("mat-input-4")).sendKeys("Nueva Notificacion")
    await driver.findElement(By.css(".ng-tns-c52-33 > .mat-form-field-infix")).click()
    await driver.findElement(By.css("#mat-option-59 > .mat-option-text")).click()
    await driver.findElement(By.css(".ng-tns-c52-35 > .mat-form-field-infix")).click()
    await driver.findElement(By.css("#mat-option-73 > .mat-option-text")).click()
    await driver.findElement(By.css(".ng-tns-c52-37 > .mat-form-field-infix")).click()
    await driver.findElement(By.css("#mat-option-76 > .mat-option-text")).click()
    await driver.findElement(By.id("mat-select-value-23")).click()
    await driver.findElement(By.css("#mat-option-77 > .mat-option-text")).click()
    await driver.findElement(By.css(".ng-tns-c52-41 > .mat-form-field-infix")).click()
    await driver.findElement(By.css("#mat-option-57 > .mat-option-text")).click()
    await driver.findElement(By.id("mat-input-6")).click()
    await driver.findElement(By.id("mat-input-6")).sendKeys("Nueva Notificación Visitas")
    {
      const element = await driver.findElement(By.css(".ng-tns-c52-31 > .mat-form-field-infix"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    {
      const element = await driver.findElement(By.css(".ng-tns-c52-31 > .mat-form-field-infix"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.css(".ng-tns-c52-31 > .mat-form-field-infix"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    await driver.findElement(By.css(".ng-tns-c52-31 > .mat-form-field-infix")).click()
    await driver.findElement(By.css(".ng-tns-c52-31 > .mat-form-field-infix")).click()
    await driver.findElement(By.css(".ng-tns-c52-31 > .mat-form-field-infix")).click()
    {
      const element = await driver.findElement(By.css(".ng-tns-c52-31 > .mat-form-field-infix"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.css(".ng-tns-c52-31 > .mat-form-field-infix")).click()
    await driver.findElement(By.id("mat-input-6")).click()
    await driver.findElement(By.id("mat-input-6")).click()
    {
      const element = await driver.findElement(By.id("mat-input-6"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.id("mat-input-6")).click()
    await driver.findElement(By.css(".ng-tns-c52-32 > .mat-form-field-infix")).click()
    await driver.findElement(By.id("mat-input-7")).sendKeys("Nueva Notificación Visitas")
    await driver.switchTo().frame(0)
    await driver.findElement(By.css("html")).click()
    {
      const element = await driver.findElement(By.id("tinymce"))
      await driver.executeScript("if(arguments[0].contentEditable === 'true') {arguments[0].innerText = '<p>Nueva Notificación Visitas:<br><br><br></p>'}", element)
    }
    await driver.switchTo().defaultContent()
    await driver.findElement(By.css("u > strong")).click()
    await driver.findElement(By.css(".mat-form-field-infix:nth-child(1)")).click()
    await driver.findElement(By.css("#mat-option-80 > .mat-option-text")).click()
    await driver.findElement(By.css(".cdk-focused")).click()
    await driver.findElement(By.css(".cdk-focused")).click()
    await driver.findElement(By.css(".cdk-focused")).click()
    await driver.executeScript("window.scrollTo(0,0)")
    await driver.findElement(By.css(".cdk-focused")).click()
  })
})
