// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('login', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').usingServer('http://localhost:4444/wd/hub').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('login', async function() {
    await driver.get("https://landing-test.vuce.gob.pe/vuce-zee-mf/#//vuce-zee-api-autorizacion/login/?urlReturn=https://landing-test.vuce.gob.pe/vuce-zee-mf/")
    await driver.manage().window().setRect({ width: 1852, height: 996 })
    await driver.findElement(By.id("username")).sendKeys("abelchingo")
    await driver.findElement(By.id("password")).sendKeys("admin")
    await driver.findElement(By.css(".btn-danger")).click()
  })
})
