// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Registro tipo de cambio', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Registro tipo de cambio', async function() {
    await driver.get("https://landing-test.vuce.gob.pe/vuce-zee-api-autorizacion/login/?urlReturn=https://landing-test.vuce.gob.pe/vuce-zee-mf/")
    await driver.manage().window().setRect({ width: 602, height: 824 })
    await driver.findElement(By.id("username")).sendKeys("abelchingo")
    await driver.findElement(By.id("password")).sendKeys("admin")
    await driver.findElement(By.id("username")).click()
    await driver.findElement(By.id("username")).click()
    {
      const element = await driver.findElement(By.id("username"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.id("password")).click()
    await driver.findElement(By.id("password")).click()
    {
      const element = await driver.findElement(By.id("password"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.css(".btn-danger")).click()
    await driver.findElement(By.css(".ng-tns-c50-38 > .text-bold-e503492c-335d-4d2a-80e6-d3348e100146")).click()
    await driver.findElement(By.css(".ng-tns-c50-128 > .second-ce6de76e-7965-48da-8a62-cabdb813e076")).click()
    await driver.findElement(By.id("mat-expansion-panel-header-73")).click()
    await driver.findElement(By.css(".cdk-focused > .mat-button-wrapper")).click()
    await driver.findElement(By.id("mat-input-4")).sendKeys("3")
    await driver.findElement(By.css(".grid-field-3 > .ng-tns-c102-19")).click()
    await driver.findElement(By.css(".grid-field-3 > .ng-tns-c102-19")).click()
    await driver.findElement(By.css(".grid-field-3 > .ng-tns-c102-19")).click()
    {
      const element = await driver.findElement(By.css(".grid-field-3 > .ng-tns-c102-19"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.css(".grid-field-3 > .ng-tns-c102-19")).click()
    await driver.findElement(By.id("mat-input-5")).click()
    await driver.findElement(By.id("mat-input-5")).sendKeys("3")
    await driver.findElement(By.css(".mat-dialog-actions")).click()
    await driver.findElement(By.css(".mat-dialog-actions")).click()
    await driver.findElement(By.css(".mat-dialog-actions")).click()
    await driver.findElement(By.css(".mat-dialog-actions")).click()
    {
      const element = await driver.findElement(By.css(".mat-dialog-actions"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.css(".cdk-focused")).click()
    await driver.findElement(By.css(".cdk-focused > .mat-button-wrapper")).click()
  })
})
