// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Registro_solicitud_control_inventario', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Registro_solicitud_control_inventario', async function() {
    await driver.get("https://landing-test.vuce.gob.pe/vuce-zee-api-autorizacion/login/?urlReturn=https://landing-test.vuce.gob.pe/vuce-zee-mf/")
    await driver.manage().window().setRect({ width: 1552, height: 832 })
    await driver.findElement(By.css(".btn-danger")).click()
    await driver.findElement(By.css(".ng-tns-c50-8 > .text-bold-e503492c-335d-4d2a-80e6-d3348e100146")).click()
    await driver.findElement(By.css(".ng-tns-c50-56 > .second-ce6de76e-7965-48da-8a62-cabdb813e076")).click()
    {
      const element = await driver.findElement(By.css("#e005159b-f348-4edc-afa2-02d8dc05d5e4 > .mat-button-wrapper"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css("#e005159b-f348-4edc-afa2-02d8dc05d5e4 > .mat-button-wrapper")).click()
    await driver.findElement(By.id("mat-input-10")).click()
    await driver.findElement(By.id("mat-input-10")).sendKeys("NET")
    await driver.findElement(By.css(".mat-option-text")).click()
    await driver.findElement(By.css("#mat-select-value-11 > .mat-select-placeholder")).click()
    await driver.findElement(By.css(".mat-option-text")).click()
    await driver.findElement(By.css(".mat-select-placeholder")).click()
    await driver.findElement(By.css("#mat-option-15 > .mat-option-text")).click()
    await driver.findElement(By.id("mat-select-value-13")).click()
    await driver.findElement(By.css("#mat-option-16 > .mat-option-text")).click()
    await driver.findElement(By.id("mat-input-9")).click()
    await driver.findElement(By.css(".ng-star-inserted:nth-child(4) > .mat-calendar-body-cell:nth-child(3) > .mat-calendar-body-cell-content")).click()
    await driver.findElement(By.css(".cdk-focused > .mat-button-wrapper")).click()
    {
      const element = await driver.findElement(By.css(".cdk-focused > .mat-button-wrapper"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".cdk-focused > .mat-button-wrapper")).click()
    await driver.findElement(By.css(".cdk-focused > .mat-button-wrapper")).click()
  })
})
