// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Vehiculo_Salida_Salidas', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Vehiculo_Salida_Salidas', async function() {
    await driver.get("https://landing-test.vuce.gob.pe/vuce-zee-api-autorizacion/login/?urlReturn=https://landing-test.vuce.gob.pe/vuce-zee-mf/")
    await driver.manage().window().setRect({ width: 1936, height: 1048 })
    await driver.findElement(By.id("username")).click()
    await driver.findElement(By.id("username")).sendKeys("info")
    await driver.findElement(By.id("password")).sendKeys("netconsultores")
    await driver.findElement(By.css(".btn-danger")).click()
    await driver.findElement(By.css(".ng-tns-c50-20 > .mat-expansion-panel-header-title")).click()
    await driver.findElement(By.css(".ng-tns-c50-80 > .second-ce6de76e-7965-48da-8a62-cabdb813e076")).click()
    await driver.findElement(By.id("mat-expansion-panel-header-40")).click()
    await driver.findElement(By.css(".cdk-focused")).click()
    await driver.findElement(By.css(".cdk-focused")).click()
    await driver.findElement(By.id("mat-input-13")).click()
    await driver.findElement(By.id("mat-input-13")).sendKeys("123")
    await driver.findElement(By.css("#mat-select-value-9 > .mat-select-placeholder")).click()
    await driver.findElement(By.css(".mat-select-search-inner > .mat-select-search-input")).sendKeys("a")
    await driver.findElement(By.css("#mat-option-406 > .mat-option-text")).click()
    await driver.findElement(By.css(".mat-select-placeholder")).click()
    await driver.findElement(By.css(".mat-select-search-inner > .mat-select-search-input")).sendKeys("x")
    await driver.findElement(By.css("#mat-option-495 > .mat-option-text")).click()
    {
      const element = await driver.findElement(By.css(".form-buttons:nth-child(2) > .mat-focus-indicator"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".cdk-focused")).click()
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.css(".ng-tns-c52-39 > .mat-form-field-infix")).click()
    await driver.findElement(By.css("#mat-option-501 > .mat-option-text")).click()
    await driver.findElement(By.css(".ng-tns-c52-41 > .mat-form-field-infix")).click()
    await driver.findElement(By.id("mat-input-14")).sendKeys("1")
    await driver.findElement(By.id("mat-input-15")).sendKeys("1")
    await driver.findElement(By.id("mat-input-16")).sendKeys("1")
    await driver.findElement(By.id("mat-input-17")).sendKeys("1")
    await driver.findElement(By.css(".cdk-focused > .mat-button-wrapper")).click()
    await driver.findElement(By.css(".ng-star-inserted > .mat-button-wrapper")).click()
    await driver.findElement(By.css(".cdk-focused")).click()
  })
})
