// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Venta_Servicios_Permanencia', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Venta_Servicios_Permanencia', async function() {
    await driver.get("https://landing-test.vuce.gob.pe/vuce-zee-api-autorizacion/login/?urlReturn=https://landing-test.vuce.gob.pe/vuce-zee-mf/")
    await driver.manage().window().setRect({ width: 1936, height: 1048 })
    await driver.findElement(By.id("username")).click()
    await driver.findElement(By.id("username")).sendKeys("info")
    await driver.findElement(By.id("password")).sendKeys("netconsultores")
    await driver.findElement(By.css(".btn-danger")).click()
    await driver.findElement(By.id("mat-expansion-panel-header-9")).click()
    await driver.findElement(By.css(".ng-tns-c50-94 > .second-ce6de76e-7965-48da-8a62-cabdb813e076")).click()
    {
      const element = await driver.findElement(By.css(".mat-raised-button:nth-child(3)"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".cdk-focused")).click()
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.css("#mat-select-value-5 > .mat-select-placeholder")).click()
    await driver.findElement(By.css(".mat-option-text")).click()
    await driver.findElement(By.css(".ng-tns-c57-25 > .mat-form-field-infix")).click()
    await driver.findElement(By.id("mat-input-7")).sendKeys("a")
    await driver.findElement(By.css("#mat-option-20 > .mat-option-text")).click()
    await driver.findElement(By.id("mat-input-8")).click()
    await driver.findElement(By.id("mat-input-8")).sendKeys("10075613137")
    await driver.findElement(By.css(".ng-tns-c57-29 > .mat-form-field-infix")).click()
    await driver.findElement(By.id("mat-input-9")).sendKeys("Teresa")
    await driver.findElement(By.css("#mat-select-value-9 > .mat-select-placeholder")).click()
    await driver.findElement(By.css("#mat-option-12 > .mat-option-text")).click()
    await driver.findElement(By.id("mat-input-10")).click()
    await driver.findElement(By.id("mat-input-10")).sendKeys("101010100")
    await driver.findElement(By.id("mat-input-11")).click()
    await driver.findElement(By.css(".ng-star-inserted:nth-child(4) > .mat-calendar-body-cell:nth-child(3) > .mat-calendar-body-cell-content")).click()
    await driver.findElement(By.css(".ng-tns-c57-34 > .mat-form-field-infix")).click()
    await driver.findElement(By.css("#mat-option-15 > .mat-option-text")).click()
    await driver.findElement(By.css(".ng-tns-c57-37 > .mat-form-field-infix")).click()
    await driver.findElement(By.id("mat-input-13")).sendKeys("1")
    await driver.findElement(By.css(".mat-select-placeholder")).click()
    await driver.findElement(By.css(".mat-option-text")).click()
    await driver.findElement(By.css(".cdk-focused")).click()
    await driver.findElement(By.css(".cdk-focused")).click()
    {
      const element = await driver.findElement(By.css(".cdk-focused"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".cdk-focused")).click()
  })
})
